99	Watt, Maureen	Aberdeen South and North Kincardine	SNP
6	Baker, Claire	Mid Scotland and Fife	Lab
86	Scott, Tavish	Shetland Islands	LD
68	McInnes, Alison	North East Scotland	LD
44	Ingram, Adam	Carrick, Cumnock and Doon Valley	SNP
59	Marra, Jenny	North East Scotland	Lab
37	Grant, Rhoda	Highlands and Islands	Lab
2	Adam, George	Paisley	SNP
131	Allard, Christian	North East Scotland	SNP
64	McArthur, Liam	Orkney Islands	LD
45	Johnstone, Alison	Lothian	Green
22	Cunningham, Roseanna	Perthshire South and Kinross-shire	SNP
76	Murray, Elaine	Dumfriesshire	Lab
129	MacKenzie, Mike	Highlands and Islands	SNP
72	McMahon, Michael	Uddingston and Bellshill	Lab
58	Malik, Hanzala	Glasgow	Lab
95	Thompson, Dave	Skye, Lochaber and Badenoch	SNP
34	FitzPatrick, Joe	Dundee City West	SNP
55	Macintosh, Ken	Eastwood	Lab
26	Dugdale, Kezia	Lothian	Lab
105	Davidson, Ruth	Glasgow	Con
74	McMillan, Stuart	West Scotland	SNP
128	McNeil, Duncan	Greenock and Inverclyde	Lab
82	Rennie, Willie	Mid Scotland and Fife	LD
5	Baillie, Jackie	Dumbarton	Lab
42	Hepburn, Jamie	Cumbernauld and Kilsyth	SNP
13	Brodie, Chic	South Scotland	SNP
97	Urquhart, Jean	Highlands and Islands	SNP
111	Mitchell, Margaret	Central Scotland	Con
18	Chisholm, Malcolm	Edinburgh Northern and Leith	Lab
19	Coffey, Willie	Kilmarnock and Irvine Valley	SNP
92	Stewart, Kevin	Aberdeen Central	SNP
3	Adamson, Clare	Central Scotland	SNP
46	Keir, Colin	Edinburgh Western	SNP
52	MacDonald, Angus	Falkirk East	SNP
35	Gibson, Kenneth	Cunninghame North	SNP
43	Hume, Jim	South Scotland	LD
32	Findlay, Neil	Lothian	Lab
117	Salmond, Alex	Aberdeenshire East	SNP
124	McAlpine, Joan	South Scotland	SNP
81	Pentland, John	Motherwell and Wishaw	Lab
118	White, Sandra	Glasgow Kelvin	SNP
132	Buchanan, Cameron	Lothian	Con
75	McTaggart, Anne	Glasgow	Lab
9	Beattie, Colin	Midlothian North and Musselburgh	SNP
66	McDonald, Mark	North East Scotland	SNP
93	Sturgeon, Nicola	Glasgow Southside	SNP
7	Baker, Richard	North East Scotland	Lab
100	Wheelhouse, Paul	South Scotland	SNP
109	McGrigor, Jamie	Highlands and Islands	Con
25	Dornan, James	Glasgow Cathcart	SNP
106	Goldie, Annabel	West Scotland	Con
87	Simpson, Dr Richard	Mid Scotland and Fife	Lab
62	Matheson, Michael	Falkirk West	SNP
107	Johnstone, Alex	North East Scotland	Con
17	Campbell, Roderick	North East Fife	SNP
125	Milne, Nanette	North East Scotland	Con
126	Grahame, Christine	Midlothian South, Tweeddale and Lauderdale	SNP
110	McLetchie, David	Lothian	Con
54	Macdonald, Lewis	North East Scotland	Lab
119	Eadie, Helen	Cowdenbeath	Lab
91	Stewart, David	Highlands and Islands	Lab
53	MacDonald, Gordon	Edinburgh Pentlands	SNP
121	Fraser, Murdo	Mid Scotland and Fife	Con
65	McCulloch, Margaret	Central Scotland	Lab
41	Henry, Hugh	Renfrewshire South	Lab
83	Robertson, Dennis	Aberdeenshire West	SNP
127	Hyslop, Fiona	Linlithgow	SNP
1	Adam, Brian	Aberdeen Donside	SNP
113	Scott, John	Ayr	Con
30	Fee, Mary	West Scotland	Lab
21	Crawford, Bruce	Stirling	SNP
88	Smith, Drew	Glasgow	Lab
120	Fergusson, Alex	Galloway and West Dumfries	Con
69	McKelvie, Christina	Hamilton, Larkhall and Stonehouse	SNP
48	Lamont, Johann	Glasgow Pollok	Lab
112	Scanlon, Mary	Highlands and Islands	Con
133	Conservativestance, Angela	Almond Valley	SNP
96	Torrance, David	Kirkcaldy	SNP
103	Brown, Gavin	Lothian	Con
15	Burgess, Margaret	Cunninghame South	SNP
16	Campbell, Aileen	Clydesdale	SNP
4	Allan, Dr Alasdair	Na h-Eileanan an Iar	SNP
80	Pearson, Graeme	South Scotland	Lab
79	Paterson, Gil	Clydebank and Milngavie	SNP
61	Mason, John	Glasgow Shettleston	SNP
49	Lochhead, Richard	Moray	SNP
115	Don, Nigel	Angus North and Mearns	SNP
23	Dey, Graeme	Angus South	SNP
89	Smith, Elaine	Coatbridge and Chryston	Lab
116	Fabiani, Linda	East Kilbride	SNP
78	Park, John	Mid Scotland and Fife	Lab
122	Kelly, James	Rutherglen	Lab
33	Finnie, John	Highlands and Islands	SNP
27	Eadie, Jim	Edinburgh Southern	SNP
12	Boyack, Sarah	Lothian	Lab
84	Robison, Shona	Dundee City East	SNP
71	McLeod, Fiona	Strathkelvin and Bearsden	SNP
67	McDougall, Margaret	West Scotland	Lab
56	Mackay, Derek	Renfrewshire North and West	SNP
38	Gray, Iain	East Lothian	Lab
130	Baxter, Jayne	Mid Scotland and Fife	Lab
8	Beamish, Claudia	South Scotland	Lab
73	McMahon, Siobhan	Central Scotland	Lab
98	Walker, Bill	Dunfermline	SNP
47	Kidd, Bill	Glasgow Anniesland	SNP
29	Ewing, Fergus	Inverness and Nairn	SNP
24	Doris, Bob	Glasgow	SNP
102	Yousaf, Humza	Glasgow	SNP
114	Smith, Liz	Mid Scotland and Fife	Con
70	McLeod, Aileen	South Scotland	SNP
40	Harvie, Patrick	Glasgow	Green
11	Bibby, Neil	West Scotland	Lab
31	Ferguson, Patricia	Glasgow Maryhill and Springburn	Lab
57	Mackenzie, Mike	Highlands and Islands	SNP
90	Stevenson, Stewart	Banffshire and Buchan Coast	SNP
85	Russell, Michael	Argyll and Bute	SNP
123	Lamont, John	Ettrick, Roxburgh and Berwickshire	Con
108	MacDonald, Margo	Lothian	Ind
60	Martin, Paul	Glasgow Provan	Lab
77	Neil, Alex	Airdrie and Shotts	SNP
20	Constance, Angela	Almond Valley	SNP
104	Carlaw, Jackson	West Scotland	Con
94	Swinney, John	Perthshire North	SNP
63	Maxwell, Stewart	West Scotland	SNP
101	Wilson, John	Central Scotland	SNP
14	Brown, Keith	Clackmannanshire and Dunblane	SNP
10	Biagi, Marco	Edinburgh Central	SNP
36	Gibson, Rob	Caithness, Sutherland and Ross	SNP
50	Lyle, Richard	Central Scotland	SNP
28	Ewing, Annabelle	Mid Scotland and Fife	SNP
39	Griffin, Mark	Central Scotland	Lab
51	MacAskill, Kenny	Edinburgh Eastern	SNP
